<a href="https://colab.research.google.com/github/antonsysoev/appl_stat/blob/gh-pages/as_Missing_data_practise_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Создадим матрицу, заполненную случайными значениями

In [93]:
a <- matrix(rnorm(100),10,10)

In [94]:
a

[,1]        [,2]        [,3]       [,4]       [,5]       [,6]      
 [1,]  1.13224212 -0.10689954 -1.4907687  1.0936388 -0.9417115  0.5910569
 [2,] -0.02468105 -1.71805970  0.2486804  0.7292913 -0.2530158 -0.7150965
 [3,] -0.30035150  0.87760954  0.7039553  0.9478543 -0.3442350 -0.1598542
 [4,] -0.04464974 -0.39888865  0.7826385 -1.9596915  1.0474862 -0.9209679
 [5,]  0.11229212 -0.31145599  0.3651376  0.5540070 -1.1075192  0.5937987
 [6,] -0.16145799  0.57344297  0.5702838  0.1774682 -0.9404782 -0.1900487
 [7,]  0.63251736 -1.30565196  0.7159008  0.4451980 -0.5662121 -0.9585040
 [8,]  0.33084721  0.06452016  1.5321218 -0.6242089  0.7492301 -0.9862198
 [9,]  1.78846836  0.07321308  1.7126904  0.9489691 -0.9586411 -0.1407585
[10,]  1.17348638  0.98675053 -0.7978397 -0.3381024 -0.3613740  2.0017531
      [,7]       [,8]       [,9]         [,10]      
 [1,] -0.7581086  0.6250922 -0.477779166  0.67162279
 [2,]  1.0074976  0.1246854  0.579590076 -1.02072320
 [3,]  0.3090536 -0.4293525  1.721600494  0.02522479
 [4,] -0.9943946 -1.2116966  0.152784511 -0.94421913
 [5,] -0.5430841  0.5264004  0.008957704  1.23302484
 [6,] -0.2910683 -0.3767606  0.799979217 -1.11378812
 [7,]  0.5139117  0.2922519 -0.056178699  0.08375163
 [8,] -1.5568880  0.9281248 -0.813175130 -1.90440047
 [9,] -3.0630638 -0.3986984 -1.201403013  0.65658303
[10,] -0.4813539 -0.5004942  1.685596134 -0.05908841

Напишем функцию для генерации заданного процента пропусков в созданной матрице

In [95]:
generate_missings <- function(a, treshold){
    for(i in 1:nrow(a)){
      for(j in 1:ncol(a)){
          if(a[i,j]<treshold){a[i,j] = NA}
      }
  }
  return(a)
}

In [96]:
x <- generate_missings(a, -1.1)
x

[,1]        [,2]        [,3]       [,4]       [,5]       [,6]      
 [1,]  1.13224212 -0.10689954         NA  1.0936388 -0.9417115  0.5910569
 [2,] -0.02468105          NA  0.2486804  0.7292913 -0.2530158 -0.7150965
 [3,] -0.30035150  0.87760954  0.7039553  0.9478543 -0.3442350 -0.1598542
 [4,] -0.04464974 -0.39888865  0.7826385         NA  1.0474862 -0.9209679
 [5,]  0.11229212 -0.31145599  0.3651376  0.5540070         NA  0.5937987
 [6,] -0.16145799  0.57344297  0.5702838  0.1774682 -0.9404782 -0.1900487
 [7,]  0.63251736          NA  0.7159008  0.4451980 -0.5662121 -0.9585040
 [8,]  0.33084721  0.06452016  1.5321218 -0.6242089  0.7492301 -0.9862198
 [9,]  1.78846836  0.07321308  1.7126904  0.9489691 -0.9586411 -0.1407585
[10,]  1.17348638  0.98675053 -0.7978397 -0.3381024 -0.3613740  2.0017531
      [,7]       [,8]       [,9]         [,10]      
 [1,] -0.7581086  0.6250922 -0.477779166  0.67162279
 [2,]  1.0074976  0.1246854  0.579590076 -1.02072320
 [3,]  0.3090536 -0.4293525  1.721600494  0.02522479
 [4,] -0.9943946         NA  0.152784511 -0.94421913
 [5,] -0.5430841  0.5264004  0.008957704  1.23302484
 [6,] -0.2910683 -0.3767606  0.799979217          NA
 [7,]  0.5139117  0.2922519 -0.056178699  0.08375163
 [8,]         NA  0.9281248 -0.813175130          NA
 [9,]         NA -0.3986984           NA  0.65658303
[10,] -0.4813539 -0.5004942  1.685596134 -0.05908841

Напищем функцию для простого восстановления пропущенных значений

In [97]:
simple_imputation <- function(a){
    mean_col <- 0
    for(j in 1:ncol(a)){
        mean_col[j] <- mean(a[,j], na.rm=TRUE)
    }
        for(j in 1:ncol(a)){
            for(i in 1:nrow(a)){
                if(is.na(a[i,j])==TRUE) {a[i,j] = mean_col[j]}
            }
        }
    return(a)
}

In [98]:
y <- simple_imputation(x)
y

[,1]        [,2]        [,3]       [,4]       [,5]       [,6]      
 [1,]  1.13224212 -0.10689954  0.6481743  1.0936388 -0.9417115  0.5910569
 [2,] -0.02468105  0.21978651  0.2486804  0.7292913 -0.2530158 -0.7150965
 [3,] -0.30035150  0.87760954  0.7039553  0.9478543 -0.3442350 -0.1598542
 [4,] -0.04464974 -0.39888865  0.7826385  0.4371239  1.0474862 -0.9209679
 [5,]  0.11229212 -0.31145599  0.3651376  0.5540070 -0.2854390  0.5937987
 [6,] -0.16145799  0.57344297  0.5702838  0.1774682 -0.9404782 -0.1900487
 [7,]  0.63251736  0.21978651  0.7159008  0.4451980 -0.5662121 -0.9585040
 [8,]  0.33084721  0.06452016  1.5321218 -0.6242089  0.7492301 -0.9862198
 [9,]  1.78846836  0.07321308  1.7126904  0.9489691 -0.9586411 -0.1407585
[10,]  1.17348638  0.98675053 -0.7978397 -0.3381024 -0.3613740  2.0017531
      [,7]       [,8]        [,9]         [,10]      
 [1,] -0.7581086  0.62509218 -0.477779166  0.67162279
 [2,]  1.0074976  0.12468540  0.579590076 -1.02072320
 [3,]  0.3090536 -0.42935254  1.721600494  0.02522479
 [4,] -0.9943946  0.08791654  0.152784511 -0.94421913
 [5,] -0.5430841  0.52640035  0.008957704  1.23302484
 [6,] -0.2910683 -0.37676061  0.799979217  0.08077204
 [7,]  0.5139117  0.29225193 -0.056178699  0.08375163
 [8,] -0.1546933  0.92812476 -0.813175130  0.08077204
 [9,] -0.1546933 -0.39869840  0.400152794  0.65658303
[10,] -0.4813539 -0.50049425  1.685596134 -0.05908841

Выполним тестирование

In [99]:
b <- generate_missings(a,-0.75)
print(b)
simple_imp <- simple_imputation(b)
print(simple_imp)

             [,1]        [,2]      [,3]       [,4]       [,5]       [,6]
 [1,]  1.13224212 -0.10689954        NA  1.0936388         NA  0.5910569
 [2,] -0.02468105          NA 0.2486804  0.7292913 -0.2530158 -0.7150965
 [3,] -0.30035150  0.87760954 0.7039553  0.9478543 -0.3442350 -0.1598542
 [4,] -0.04464974 -0.39888865 0.7826385         NA  1.0474862         NA
 [5,]  0.11229212 -0.31145599 0.3651376  0.5540070         NA  0.5937987
 [6,] -0.16145799  0.57344297 0.5702838  0.1774682         NA -0.1900487
 [7,]  0.63251736          NA 0.7159008  0.4451980 -0.5662121         NA
 [8,]  0.33084721  0.06452016 1.5321218 -0.6242089  0.7492301         NA
 [9,]  1.78846836  0.07321308 1.7126904  0.9489691         NA -0.1407585
[10,]  1.17348638  0.98675053        NA -0.3381024 -0.3613740  2.0017531
            [,7]       [,8]         [,9]       [,10]
 [1,]         NA  0.6250922 -0.477779166  0.67162279
 [2,]  1.0074976  0.1246854  0.579590076          NA
 [3,]  0.3090536 -0.4293525  1.7216004

Воспользуемся стандартыми методами восстановления пропущенных значений

In [100]:
install.packages("mice")
library(mice)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [101]:
tempData <- mice(b,m=5,maxit=50,meth='mean',seed=500)


 iter imp variable
  1   1  V2  V3  V4  V5  V6  V7  V8  V9  V10
  1   2  V2  V3  V4  V5  V6  V7  V8  V9  V10
  1   3  V2  V3  V4  V5  V6  V7  V8  V9  V10
  1   4  V2  V3  V4  V5  V6  V7  V8  V9  V10
  1   5  V2  V3  V4  V5  V6  V7  V8  V9  V10
  2   1  V2  V3  V4  V5  V6  V7  V8  V9  V10
  2   2  V2  V3  V4  V5  V6  V7  V8  V9  V10
  2   3  V2  V3  V4  V5  V6  V7  V8  V9  V10
  2   4  V2  V3  V4  V5  V6  V7  V8  V9  V10
  2   5  V2  V3  V4  V5  V6  V7  V8  V9  V10
  3   1  V2  V3  V4  V5  V6  V7  V8  V9  V10
  3   2  V2  V3  V4  V5  V6  V7  V8  V9  V10
  3   3  V2  V3  V4  V5  V6  V7  V8  V9  V10
  3   4  V2  V3  V4  V5  V6  V7  V8  V9  V10
  3   5  V2  V3  V4  V5  V6  V7  V8  V9  V10
  4   1  V2  V3  V4  V5  V6  V7  V8  V9  V10
  4   2  V2  V3  V4  V5  V6  V7  V8  V9  V10
  4   3  V2  V3  V4  V5  V6  V7  V8  V9  V10
  4   4  V2  V3  V4  V5  V6  V7  V8  V9  V10
  4   5  V2  V3  V4  V5  V6  V7  V8  V9  V10
  5   1  V2  V3  V4  V5  V6  V7  V8  V9  V10
  5   2  V2  V3  V4  V5  V6  V7  V8

Warning message:
“Number of logged events: 2295”


In [102]:
summary(tempData)

Class: mids
Number of multiple imputations:  5 
Imputation methods:
    V1     V2     V3     V4     V5     V6     V7     V8     V9    V10 
    "" "mean" "mean" "mean" "mean" "mean" "mean" "mean" "mean" "mean" 
PredictorMatrix:
   V1 V2 V3 V4 V5 V6 V7 V8 V9 V10
V1  0  1  1  1  1  1  1  1  1   1
V2  1  0  1  1  1  1  1  1  1   1
V3  1  1  0  1  1  1  1  1  1   1
V4  1  1  1  0  1  1  1  1  1   1
V5  1  1  1  1  0  1  1  1  1   1
V6  1  1  1  1  1  0  1  1  1   1
Number of logged events:  2295 
  it im dep meth                                                out
1  1  1  V2 mean df set to 1. # observed cases: 8  # predictors: 10
2  1  1  V2 mean                                             V3, V9
3  1  1  V3 mean df set to 1. # observed cases: 8  # predictors: 10
4  1  1  V3 mean                                             V2, V6
5  1  1  V4 mean df set to 1. # observed cases: 9  # predictors: 10
6  1  1  V4 mean                                             V1, V3


In [90]:
tempData$imp

$V1
          1         2         3         4         5
1 0.2308193 0.2308193 0.2308193 0.2308193 0.2308193
7 0.2308193 0.2308193 0.2308193 0.2308193 0.2308193

$V2
            1           2           3           4           5
2 -0.04361406 -0.04361406 -0.04361406 -0.04361406 -0.04361406
4 -0.04361406 -0.04361406 -0.04361406 -0.04361406 -0.04361406

$V3
         1        2        3        4        5
2 1.092209 1.092209 1.092209 1.092209 1.092209
3 1.092209 1.092209 1.092209 1.092209 1.092209
6 1.092209 1.092209 1.092209 1.092209 1.092209

$V4
          1         2         3         4         5
1 0.8145567 0.8145567 0.8145567 0.8145567 0.8145567

$V5
          1         2         3         4         5
1 0.1597151 0.1597151 0.1597151 0.1597151 0.1597151
2 0.1597151 0.1597151 0.1597151 0.1597151 0.1597151

$V6
         1        2        3        4        5
6 0.468047 0.468047 0.468047 0.468047 0.468047

$V7
          1         2         3         4         5
2 0.1909516 0.1909516 0.1909516 0.1909516 0.1909516
3 0.1909516 0.1909516 0.1909516 0.1909516 0.1909516
4 0.1909516 0.1909516 0.1909516 0.1909516 0.1909516

$V8
          1         2         3         4         5
3 0.4238953 0.4238953 0.4238953 0.4238953 0.4238953
8 0.4238953 0.4238953 0.4238953 0.4238953 0.4238953

$V9
          1         2         3         4         5
2 0.3845973 0.3845973 0.3845973 0.3845973 0.3845973
5 0.3845973 0.3845973 0.3845973 0.3845973 0.3845973

$V10
            1           2           3           4           5
1 -0.01250661 -0.01250661 -0.01250661 -0.01250661 -0.01250661
2 -0.01250661 -0.01250661 -0.01250661 -0.01250661 -0.01250661
4 -0.01250661 -0.01250661 -0.01250661 -0.01250661 -0.01250661
6 -0.01250661 -0.01250661 -0.01250661 -0.01250661 -0.01250661

In [91]:
mult_imp <- complete(tempData,1)

mult_imp

V1          V2          V3           V4          V5         V6        
1   0.23081926 -0.51115640  2.804142245  0.81455668  0.1597151  2.4690652
2  -0.74191395 -0.04361406  1.092209078  0.30207755  0.1597151  0.1956537
3   0.05879601  0.22831470  1.092209078  1.67742221 -0.3311791  0.8312410
4  -0.13990997 -0.04361406  1.140793639  0.08873922 -0.2935169 -0.0917790
5   0.27292865  0.34587679 -0.267221316 -0.11699875 -0.5792522 -0.5932073
6   0.41328223 -0.56945465  1.092209078  0.73186987 -0.6339134  0.4680470
7   0.23081926  0.22363462  1.169051085  1.33118222  3.2446274  1.4165619
8   1.15824624  0.80387808  0.006890169  1.62128944  0.4411658 -0.7169899
9   0.94523423 -0.58091247  1.803165811  1.51861306 -0.4687702  0.1903073
10 -0.12010939 -0.28909317  0.988641910  0.17681525 -0.1014405  0.5115703
   V7         V8         V9         V10        
1  -0.2815004  0.3551589 -0.4745367 -0.01250661
2   0.1909516  1.7727127  0.3845973 -0.01250661
3   0.1909516  0.4238953 -0.6131476  0.16678177
4   0.1909516  0.7687810  0.9426291 -0.01250661
5   0.6476791 -0.2771815  0.3845973  0.22155404
6   0.5907879  0.5226356  1.0881268 -0.01250661
7   0.8988205 -0.6119835 -0.7172982 -0.19339694
8  -0.3184443  0.4238953  0.1814625  0.29303790
9  -0.4025609  0.5388541  0.5399106 -0.69911341
10  0.2018793  0.3221846  2.1296316  0.13609695

Задание 1: напишите функция для сравнения методов

In [92]:
# Ваше решение здесь

compare <- function(a, b){
    sum <- 0
    for(i in 1:nrow(a)){
      for(j in 1:ncol(a)){
          sum = sum + (a[i,j]-b[i,j])^2
      }
  }
  return(sum)
}


In [79]:
compare(a,simple_imp)

[1] 76.18022

In [103]:
compare(a, mult_imp)

[1] 135.2814

In [55]:
simple_imp

[,1]       [,2]       [,3]       [,4]       [,5]        [,6]       
 [1,]  0.4708512 -0.4774477 -0.4291115 -0.1816263 -0.52345427 -0.07619319
 [2,]  0.5545494  0.5185910 -0.4783341  2.1583979 -0.39561333  1.07536957
 [3,]  0.2699472  1.5153921 -0.2684894  2.0918254 -0.04477162 -0.42241491
 [4,]  1.0059223 -0.6143065  0.5037540  1.1464610 -0.04477162  1.17158265
 [5,] -0.3463302 -0.1214299  0.8505474  0.1744130 -0.04477162 -0.49902720
 [6,]  0.6940689  0.5150280  0.5037540 -0.3882045  0.55290580  0.06725933
 [7,]  0.5545494  0.7910149  1.7795581  0.6847333 -0.04477162 -0.07267393
 [8,]  1.5298753  0.6144846  0.7251745  0.6847333 -0.49761287  0.06725933
 [9,]  0.2575113  0.3426658  0.5688617  0.6847333  0.80875883 -0.32511072
[10,]  0.5545494  0.3426658  1.2818252 -0.2081334 -0.21361385 -0.31345761
      [,7]        [,8]        [,9]        [,10]     
 [1,]  1.60983594  1.09900781  0.91952056 -0.6339771
 [2,]  0.66340700 -0.11171243  0.20928607  1.2371233
 [3,]  0.86427600  0.33059812  0.82067531  0.3650680
 [4,]  0.25304135 -0.33330541  0.43851738  0.3650680
 [5,] -0.70392589  1.45038998  0.20928607  0.1787487
 [6,]  0.69109464 -0.03255450  0.09178732 -0.6499202
 [7,]  0.03159485  0.52397742 -0.53316756 -0.3230062
 [8,] -0.74983664 -0.30586438 -0.48161662 -0.6782463
 [9,] -0.55206711 -0.26372831  0.20928607  1.1723277
[10,]  0.42299341  0.08458039  0.20928607  2.6174944

Задание 2: постройте модель линейной множественной регрессии на исходном наборе с данными (без пропусков) и на наборе с данными после восстановления. Проанализируйте полученные результаты ($R^2$, $F$-статистика).

In [106]:
# Ваше решение здесь

data_comp <- as.data.frame(a)
data_imputed_mean <- simple_imp
data_imputed_base <- mult_imp

linear_polnaya <- lm(V1 ~., data_comp)
linear_mean <- lm(V1 ~., data_imputed_mean)
linear_base <- lm(V1 ~., data_imputed_base)

Опишите выводы в этом поле